from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Input
# ---------------------------------------------------------------------------

Industry = Literal[
    "Financial Services",
    "Healthcare",
    "Technology",
    "Energy",
    "Retail",
    "Manufacturing",
    "Government",
    "Telecommunications",
    "Real Estate",
    "Education",
]

ListedStatus = Literal["Public", "Private", "Government"]

AuditTopic = Literal[
    "Cybersecurity",
    "Data Privacy",
    "Financial Reporting",
    "Vendor Management",
    "Business Continuity",
    "IT General Controls",
    "Anti-Money Laundering",
    "ESG & Sustainability",
    "Operational Risk",
]


class AuditInput(BaseModel):
    company_name: str
    industry: Industry
    country: str
    listed_status: ListedStatus
    audit_topic: AuditTopic


# ---------------------------------------------------------------------------
# Output building blocks
# ---------------------------------------------------------------------------

Priority = Literal["Critical", "High", "Medium", "Low"]
RiskRating = Literal["Critical", "High", "Medium", "Low"]
RemediationEffort = Literal["Low", "Medium", "High", "Very High"]


class ControlObjective(BaseModel):
    control_id: str = Field(description="Short unique ID, e.g. ISO-AC-01")
    description: str = Field(description="What the control requires")
    requirement_source: str = Field(description="Clause / section reference, e.g. ISO 27001 A.8.3")
    testing_approach: str = Field(description="How an auditor would test this control")
    priority: Priority


class FrameworkAssessment(BaseModel):
    framework_name: str
    applicability_rationale: str = Field(
        description="Why this framework applies to the given inputs"
    )
    control_objectives: list[ControlObjective]
    key_gaps: list[str] = Field(description="Typical gaps for this profile")
    risk_rating: RiskRating


class RegulatoryRequirement(BaseModel):
    regulation_name: str
    jurisdiction: str
    mandatory: bool
    applicable_sections: list[str]
    compliance_notes: str = Field(
        description="Key compliance obligations or deadlines"
    )


class GapRiskSummary(BaseModel):
    overall_risk_rating: RiskRating
    critical_gaps: list[str]
    recommended_priority_actions: list[str]
    estimated_remediation_effort: RemediationEffort
    executive_summary: str = Field(
        description="2-3 sentence plain-English summary for non-technical stakeholders"
    )


# ---------------------------------------------------------------------------
# Top-level report
# ---------------------------------------------------------------------------

class ComplianceReport(BaseModel):
    report_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    generated_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    audit_input: AuditInput
    mandatory_regulations: list[RegulatoryRequirement]
    framework_assessments: list[FrameworkAssessment]
    gap_risk_summary: GapRiskSummary
    disclaimer: str = Field(
        default=(
            "This report is generated by an AI system and is intended as a "
            "starting point for internal audit planning. It does not constitute "
            "legal or professional compliance advice. Always engage qualified "
            "compliance professionals to confirm regulatory obligations."
        )
    )
